### ISSUE TITLE
Bootstrap 4 show/hide classes

### ISSUE THREAD

**Issue by rupasix** [patrykgruszka/responsive-breakpoint-tester#1]
Bootstrap 4 after alpha have changed classes again:
https://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements
Consider changing your default classTemplate to 'd-none d-{device}-block'.

ps. nice script, good job!

**Comment by patrykgruszka** [comment]
Thank you for reporting this issue. Your resolution is not 100% correct, because we have to provide element class that is visible only on requested device.
E.q. `d-none d-sm-block` will return positive for `sm`, `md`, `lg` and `xl` devices.

I'm afraid that version 1.1.0 is not compatible with Bootstrap 4. 
I've updated the device testing rules and relesed version 2.0.0 of this utility with default Bootstrap 4 settings.
